In [1]:
import numpy as np 
from sklearn.linear_model import LinearRegression

In [2]:
# Step 2a: Provide data
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [3]:
y = np.array([5, 20, 14, 32, 22, 38])
y

array([ 5, 20, 14, 32, 22, 38])

In [4]:
# Step 3: Create a model and fit it
model = LinearRegression()
model.fit(x, y)

LinearRegression()

In [5]:
# Step 4: Get results
r_sq = model.score(x, y)

In [6]:
print('coefficient of determination:', r_sq)
print('intercept:', model.intercept_)
print('slope:', model.coef_)

coefficient of determination: 0.715875613747954
intercept: 5.633333333333333
slope: [0.54]


In [7]:
# this is the data which we will use for predict
k= np.array([4, 12, 20, 32, 42, 53]).reshape((-1, 1))

In [8]:
# Step 5: Predict
test1 = model.predict(k)

In [9]:
test1

array([ 7.79333333, 12.11333333, 16.43333333, 22.91333333, 28.31333333,
       34.25333333])